In [1]:
import numpy as np

In [2]:
array_reloaded = np.load('DATA_S2/S2_10000.npy')

In [3]:
print(array_reloaded)
print('\nShape: ',array_reloaded.shape)

[[[[ -237  -236  -196 ...  8762  9313  9727]
   [ -242  -218  -209 ...  8773  8968  9413]
   [ -236  -211  -221 ...  9046  8849  9109]
   ...
   [  188   165   197 ...   230   244   278]
   [  181   246   252 ...   247   261   382]
   [  150   245   374 ...   217   302   490]]

  [[    0     0     0 ...  8777  9387  9752]
   [    0     0     0 ...  8707  9166  9565]
   [    0     0     0 ...  8899  8914  9268]
   ...
   [  340   388   389 ...   486   471   586]
   [  421   486   505 ...   483   450   705]
   [  350   488   635 ...   511   466   849]]

  [[    0     0     0 ...  9006  9660  9928]
   [    0     0     0 ...  8930  9485  9919]
   [    0     0     0 ...  8950  9204  9661]
   ...
   [  199   211   225 ...   386   435   417]
   [  278   347   285 ...   427   404   583]
   [  166   305   433 ...   423   432   813]]

  ...

  [[  696   651   589 ...  9807 10098 10377]
   [  715   677   628 ...  9833 10060 10344]
   [  726   688   650 ...  9820  9951 10246]
   ...
   [ 5514  546